server:
  port: 9090
spring:
  messages:
    basename: i18n/messages
#日志配置
logging:
  config: classpath:logback-spring.xml
#  #mogodb 配置
#  data:
#    mongodb:
#      uri: mongodb://api:_api%40OCTV@devops.octvv.com:27017/im?main?authSource=admin&authMechanism=SCRAM-SHA-1
#  # redis 配置
#  redis:
#    # 地址 127.0.0.1
#    database: 5
#    host: devops.octvv.com
#    # 端口，默认为6379
#    port: 6379
#    # 密码 正式环境密码 octV@123
#    password: redis_99
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 10
#        # 连接池的最大数据库连接数
#        max-active: 10
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
#
#
#rocketmq:
#  #nameservice服务器地址（多个以英文逗号隔开）
#  name-server: devops.octvv.com:9876
#  #生产者配置
#  producer:
#    #组名
#    group: octv-im-group
#    max-message-size: 4194304
#    ##生产者发送消息超时时间,默认3s
#    send-message-timeout: 5000
#    retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数。默认为 2 次。
#    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次。
#    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
#
## MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.octv.**.entity
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mybatisMapper/*.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatisMapper/config/mybatis-config.xml
#
## 聊天服务配置
#octv:
#  im-chat-server:
#    ssl:
#      model: 0 #0 不走ssl 1 ssl 认证
#      keystore: test
#      truststore: test
#      password: 0000
#    port: 8192    # 服务监听端口
#    offLine-message-limit: 1000 #离线消息限制   前1000条
#    heat-beat-time:  6000 #心跳超时时间，单位：毫秒
#    protocol-name: octv-im  #协议名字(可以随便取，主要用于开发人员辨识)
#    upload-images-type: png, jpg, bmp, jpeg, gif #支持的图片上传类型
#    upload-images-path: C:/Users/wsh/Desktop/test/
#    open-cluster: false  #开启集群
#
